'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.34209
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace ServiceClientes
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="ServiceClientes.IServicioCliente")>  _
    Public Interface IServicioCliente
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IServicioCliente/ClienteListar", ReplyAction:="http://tempuri.org/IServicioCliente/ClienteListarResponse")>  _
        Function ClienteListar() As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IServicioCliente/ClienteListar", ReplyAction:="http://tempuri.org/IServicioCliente/ClienteListarResponse")>  _
        Function ClienteListarAsync() As System.Threading.Tasks.Task(Of System.Data.DataSet)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IServicioCliente/PedidosCliente", ReplyAction:="http://tempuri.org/IServicioCliente/PedidosClienteResponse")>  _
        Function PedidosCliente(ByVal idcli As String) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IServicioCliente/PedidosCliente", ReplyAction:="http://tempuri.org/IServicioCliente/PedidosClienteResponse")>  _
        Function PedidosClienteAsync(ByVal idcli As String) As System.Threading.Tasks.Task(Of System.Data.DataSet)
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface IServicioClienteChannel
        Inherits ServiceClientes.IServicioCliente, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class ServicioClienteClient
        Inherits System.ServiceModel.ClientBase(Of ServiceClientes.IServicioCliente)
        Implements ServiceClientes.IServicioCliente
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function ClienteListar() As System.Data.DataSet Implements ServiceClientes.IServicioCliente.ClienteListar
            Return MyBase.Channel.ClienteListar
        End Function
        
        Public Function ClienteListarAsync() As System.Threading.Tasks.Task(Of System.Data.DataSet) Implements ServiceClientes.IServicioCliente.ClienteListarAsync
            Return MyBase.Channel.ClienteListarAsync
        End Function
        
        Public Function PedidosCliente(ByVal idcli As String) As System.Data.DataSet Implements ServiceClientes.IServicioCliente.PedidosCliente
            Return MyBase.Channel.PedidosCliente(idcli)
        End Function
        
        Public Function PedidosClienteAsync(ByVal idcli As String) As System.Threading.Tasks.Task(Of System.Data.DataSet) Implements ServiceClientes.IServicioCliente.PedidosClienteAsync
            Return MyBase.Channel.PedidosClienteAsync(idcli)
        End Function
    End Class
End Namespace
